Add missing python-setuptools dependency
The 03a-build-glib step requires python-setuptools to fix this error:

ModuleNotFoundError: No module named 'distutils'